<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="LAPTOP-6C34LHA8" failures="1" tests="1" name="Default test" time="3.966" errors="0" timestamp="2024-05-20T21:35:11 IST">
  <testcase classname="com.sevenrmartsupermarket.tests.AdminUsersTest" name="verifyNewAdminUserCreated" time="1.55">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.sevenrmartsupermarket.tests.AdminUsersTest.verifyNewAdminUserCreated(AdminUsersTest.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyNewAdminUserCreated -->
  <testcase classname="com.sevenrmartsupermarket.tests.AdminUsersTest" name="verifyUserProfileDeletion" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUserProfileDeletion -->
  <testcase classname="com.sevenrmartsupermarket.tests.AdminUsersTest" name="verifyEditUserDetailsFunctionality" time="0.0">
    <ignored/>
  </testcase> <!-- verifyEditUserDetailsFunctionality -->
  <testcase classname="com.sevenrmartsupermarket.tests.AdminUsersTest" name="verifyUsernameAlreadyExistAlertMessage" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUsernameAlreadyExistAlertMessage -->
  <testcase classname="com.sevenrmartsupermarket.tests.AdminUsersTest" name="verifyNewlyCreatedAdminLogo" time="0.0">
    <ignored/>
  </testcase> <!-- verifyNewlyCreatedAdminLogo -->
  <testcase classname="com.sevenrmartsupermarket.tests.AdminUsersTest" name="verifyUserDeactivation" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUserDeactivation -->
</testsuite> <!-- Default test -->
